teamName: kubrix
appName: ehwuascht
repoUrl: https://github.com/kubriX-demo/kubrix-ehwuascht
appNamespace:
  create: true
  labels:
    kubrix.io/kyverno: kubevirt-rolebinding
stages:
  - name: "test"
    requestedFreight:
    - origin:
        kind: Warehouse
        name: warehouse-{{ .Values.appName }}
      sources:
        direct: true
  - name: "qa"
    requestedFreight:
    - origin:
        kind: Warehouse
        name: warehouse-{{ .Values.appName }}
      sources:
        stages:
        - test
  - name: "prod"
    openPr: true
    requestedFreight:
    - origin:
        kind: Warehouse
        name: warehouse-{{ .Values.appName }}
      sources:
        stages:
        - qa
